# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Bennet\PycharmProjects\shortcuts\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, controller):
        self.controller = controller
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 559)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.macros_table = QtWidgets.QTableWidget(self.centralwidget)
        self.macros_table.setGeometry(QtCore.QRect(0, 40, 571, 441))
        self.macros_table.setObjectName("macros_table")
        self.macros_table.setColumnCount(3)
        self.macros_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.macros_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.macros_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.macros_table.setHorizontalHeaderItem(2, item)
        self.macros_table.horizontalHeader().setCascadingSectionResizes(False)
        self.macros_table.horizontalHeader().setDefaultSectionSize(180)
        self.macros_table.horizontalHeader().setSortIndicatorShown(False)
        self.macros_table.horizontalHeader().setStretchLastSection(True)
        self.macros_table.verticalHeader().setStretchLastSection(False)
        self.load_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_btn.setGeometry(QtCore.QRect(410, 490, 75, 23))
        self.load_btn.setCheckable(False)
        self.load_btn.setObjectName("load_btn")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(490, 490, 75, 23))
        self.save_btn.setObjectName("save_btn")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(10, 490, 75, 23))
        self.add_btn.setObjectName("add_btn")
        self.category_box = QtWidgets.QComboBox(self.centralwidget)
        self.category_box.setGeometry(QtCore.QRect(0, 10, 181, 22))
        self.category_box.setObjectName("category_box")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 578, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.save_btn.clicked.connect(self.controller.save)
        self.load_btn.clicked.connect(self.controller.load)
        self.add_btn.clicked.connect(self.controller.add)
        self.category_box.currentIndexChanged.connect(self.controller.category_changed)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MacroEditor"))
        item = self.macros_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Trigger"))
        item = self.macros_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Parameters"))
        item = self.macros_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Response"))
        self.load_btn.setText(_translate("MainWindow", "Load"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.add_btn.setText(_translate("MainWindow", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
